### PR TITLE
Initial structure for projects.json

### PR DESCRIPTION
**Pull request by kevinelliott**
We can likely add additional attributes to this as we need them. Once we've agreed on the structure of this file, I will add some additional projects in here (namely, SalsaDAO, PLENTY, etc).

### CODE REVIEW

**Comment by jmagly** [comment]
would you like this to be pushed up as a new static endpoint?

**Comment by kevinelliott** [comment]
Yes that would be great. If we need internal references (and not just community overrides) we should prob set that up too.

**Comment by jmagly** [comment]
going to strive to key all data the same way the chain does and base both primary and foreign keys that way except in cases where integer indexing can give a significant enough boost for a particular usecase. 

this looks good to start, ill load it up!

**Comment by jmagly** [comment]
https://api.teztools.io/v1/projects

**Pull request merged**
